[package]
name = "rstb"
version = "0.1.0"
authors = ["Caleb Smith <macadamiadaze@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "1.0.1"
binwrite = "0.2.1"
cached = "0.13.1"
crc = "1.8.1"
csv = "1.1.3"
indexmap = { version = "1.4.0", features = ["serde-1"] }
lazy_static = "1.4.0"
parse_int = "0.4.0"
serde = { version = "1.0.112", features = ["derive"] }
serde_derive = "1.0.112"
serde_json = "1.0.55"
yaz0 = "0.1.2"