[package]
name = "rstb"
version = "0.1.1"
description = "Rust library for manipulating Breath of the Wild's resource size table"
homepage = "https://github.com/NiceneNerd/rstb-rust"
readme = "README.md"
keywords = ["Nintendo", "rstb", "Zelda", "botw", "gamedev"]
categories = ["parsing", "game-development"]
license = "MIT"
authors = ["Caleb Smith <macadamiadaze@gmail.com>"]
edition = "2018"

[dependencies]
binread = "1.0.1"
binwrite = "0.2.1"
cached = "0.13.1"
crc = "1.8.1"
csv = "1.1.3"
indexmap = { version = "1.4.0", features = ["serde-1"] }
lazy_static = "1.4.0"
parse_int = "0.4.0"
serde = { version = "1.0.112", features = ["derive"] }
serde_derive = "1.0.112"
serde_json = "1.0.55"
yaz0 = "0.1.2"
